name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]   # adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker REGION-docker.pkg.dev --quiet
        # Example REGION: us-central1

      - name: Build and Push Docker image
        run: |
          IMAGE="REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/SERVICE_NAME:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE="REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/SERVICE_NAME:latest"
          gcloud run deploy SERVICE_NAME \
            --image $IMAGE \
            --region REGION \
            --platform managed \
            --allow-unauthenticated
